version: '3'

services:
  rabbitmq:
    build: docker/rabbitmq
    container_name: rabbitmq_minotaur
    environment:
      RABBITMQ_DEFAULT_USER: ""
      RABBITMQ_DEFAULT_PASS: ""
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "./app:/tools/app"
      - "./docker/input:/tools/input"
      - "./docker/output:/tools/output"

  amass:
    build: docker/amass
    container_name: amass_minotaur
    depends_on:
      - rabbitmq
    volumes:
      - "./app:/tools/app"
      - "./docker/input:/tools/input"
      - "./docker/output:/tools/output"

  assetfinder:
    build: docker/assetfinder
    container_name: assetfinder_minotaur
    depends_on:
      - rabbitmq
    volumes:
      - "./app:/tools/app"
      - "./docker/input:/tools/input"
      - "./docker/output:/tools/output"
    env_file:
      - env

  findomain:
    build: docker/findomain
    container_name: findomain_minotaur
    depends_on:
      - rabbitmq
    volumes:
      - "./app:/tools/app"
      - "./docker/input:/tools/input"
      - "./docker/output:/tools/output"

  subfinder:
    build: docker/subfinder
    container_name: subfinder_minotaur
    depends_on:
      - rabbitmq
    volumes:
      - "./app:/tools/app"
      - "./docker/input:/tools/input"
      - "./docker/output:/tools/output"

  resolve:
    build: docker/resolve
    container_name: resolve_minotaur
    depends_on:
      - rabbitmq
    volumes:
      - "./app:/tools/app"
      - "./docker/input:/tools/input"
      - "./docker/output:/tools/output"

#  brute:
#    build: docker/brute
#    container_name: brute_minotaur
#    depends_on:
#      - rabbitmq
#    volumes:
#      - "./app:/tools/app"
#      - "./docker/input:/tools/input"
#      - "./docker/output:/tools/output"

  httprobe:
    build: docker/httprobe
    depends_on:
      - rabbitmq
    deploy:
      mode: replicated
      replicas: 4
    volumes:
      - "./app:/tools/app"
      - "./docker/input:/tools/input"
      - "./docker/output:/tools/output"
  
  dedup:
    build: docker/dedup
    container_name: dedup_minotaur
    depends_on:
      - rabbitmq
    volumes:
      - "./app:/tools/app"
      - "./docker/input:/tools/input"
      - "./docker/output:/tools/output"

  gowitness:
    build: docker/gowitness
    container_name: gowitness_minotaur
    depends_on:
      - rabbitmq
    volumes:
      - "./app:/tools/app"
      - "./docker/input:/tools/input"
      - "./docker/output:/tools/output"

  dir-scan:
    build: docker/dir-scan
    depends_on:
      - rabbitmq
    deploy:
      mode: replicated
      replicas: 5
    volumes:
      - "./app:/tools/app"
      - "./docker/input:/tools/input"
      - "./docker/output:/tools/output"

  ipscan:
    build: docker/ipscan
    depends_on:
      - rabbitmq
    deploy:
      mode: replicated
      replicas: 3
    volumes:
      - "./app:/tools/app"
      - "./docker/input:/tools/input"
      - "./docker/output:/tools/output"
#    environment:
#      - LC_ALL=C.UTF-8
#      - LANG=C.UTF-8
